version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    env_file: .env
    environment:
      REDIS_URL: redis://redis:6379
    image: cat
    volumes:
      - .:/usr/src/app:cached
      - bundle:/usr/local/bundle
  redis:
    image: redis:alpine
volumes:
  bundle:
